/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import informacion.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Ventana para añadir unidades
 *
 * @author Rafael Navarro Prieto
 * @version 1.0
 */
public class AltaUnidad extends javax.swing.JDialog {

    /**
     * clase que se utiliza para los mensajes de error o de información
     */
    protected final JPanel contentPanel = new JPanel();
    /**
     * Ventana principal
     */
    JFrame ventanaPrincipal;

    /**
     * Constructor
     *
     * @param principal ventana principal
     */
    public AltaUnidad(JFrame principal) {
        initComponents();
        setTitle(Intermediaria.archivo.getName()+"- A\u00F1adir unidad - 09-may-2015");
        this.ventanaPrincipal = principal;
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        raza = new javax.swing.ButtonGroup();
        tipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        protos = new javax.swing.JRadioButton();
        zerg = new javax.swing.JRadioButton();
        terran = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        mediana = new javax.swing.JRadioButton();
        pesada = new javax.swing.JRadioButton();
        ligera = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(610, 500));
        setMinimumSize(new java.awt.Dimension(610, 500));
        setPreferredSize(new java.awt.Dimension(610, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Raza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Starcraft", 0, 10), new java.awt.Color(0, 0, 204))); // NOI18N

        raza.add(protos);
        protos.setSelected(true);
        protos.setText("Protos");
        protos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zergStateChanged(evt);
            }
        });

        raza.add(zerg);
        zerg.setText("Zerg");
        zerg.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zergStateChanged(evt);
            }
        });

        raza.add(terran);
        terran.setText("Terran");
        terran.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zergStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zerg)
                    .addComponent(terran)
                    .addComponent(protos))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(protos)
                .addGap(18, 18, 18)
                .addComponent(terran)
                .addGap(18, 18, 18)
                .addComponent(zerg)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Starcraft", 0, 10), new java.awt.Color(0, 0, 255))); // NOI18N

        tipo.add(mediana);
        mediana.setText("Mediana");
        mediana.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ligeraStateChanged(evt);
            }
        });

        tipo.add(pesada);
        pesada.setText("Pesada");
        pesada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ligeraStateChanged(evt);
            }
        });

        tipo.add(ligera);
        ligera.setSelected(true);
        ligera.setText("Ligera");
        ligera.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ligeraStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ligera)
                    .addComponent(mediana)
                    .addComponent(pesada))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ligera)
                .addGap(18, 18, 18)
                .addComponent(mediana)
                .addGap(18, 18, 18)
                .addComponent(pesada)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Starcraft", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");

        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        cancelar.setText("Salir");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addComponent(nombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crear)
                            .addComponent(cancelar)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 490, 160));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otros/zealot.png"))); // NOI18N
        imagen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 102)));
        imagen.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otros/FondoFinal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 680, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        try {
            Intermediaria.lista.annadir(nombre.getText(), comprobarTipo(), comprobarRaza());
            JOptionPane.showMessageDialog(contentPanel, "Unidad creada", "Info", JOptionPane.INFORMATION_MESSAGE);
            nombre.setText("");
        } catch (NombreNoValidoException | UnidadRepetidaException ex) {
            JOptionPane.showMessageDialog(contentPanel, ex.getMessage(), "ERROR!!!!", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_crearActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        dispose();
        ventanaPrincipal.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void zergStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zergStateChanged
        modificarImagenTipo(comprobarRaza());
    }//GEN-LAST:event_zergStateChanged

    private void ligeraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ligeraStateChanged
        modificarImagenRaza(comprobarTipo());
    }//GEN-LAST:event_ligeraStateChanged
    /**
     * Compruena el radio seleccionado con respecto al tipo de unidad
     *
     * @return devuelve Tipo.LIGERA si el radio seleccionado es
     * ligera,Tipo.MEDIANA si el radio seleccionado es MEDIANA o Tipo.PESADA si
     * el radio seleccionado es pesada
     */
    private Tipo comprobarTipo() {
        if (ligera.isSelected()) {
            return Tipo.LIGERA;
        } else if (mediana.isSelected()) {
            return Tipo.MEDIANA;
        } else {
            return Tipo.PESADA;
        }
    }

    /**
     * Compruena el radio seleccionado con respecto a la raza de la unidad
     *
     * @return devuelve Raza.PROTOS si el radio seleccionado es
     * protos,Tipo.TERRAN si el radio seleccionado es terran o Tipo.ZERG si el
     * radio seleccionado es zerg
     */
    private Raza comprobarRaza() {
        if (protos.isSelected()) {
            return Raza.PROTOS;
        } else if (terran.isSelected()) {
            return Raza.TERRAN;
        } else {
            return Raza.ZERG;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton crear;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton ligera;
    private javax.swing.JRadioButton mediana;
    private javax.swing.JTextField nombre;
    private javax.swing.JRadioButton pesada;
    private javax.swing.JRadioButton protos;
    private javax.swing.ButtonGroup raza;
    private javax.swing.JRadioButton terran;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.JRadioButton zerg;
    // End of variables declaration//GEN-END:variables
   /**
     * Al cerrar el programa
     */
    private void cerrar() {
        ventanaPrincipal.setVisible(true);
        dispose();
    }
    /**
     * Modifica la imagen segun la raza seleccionada
     * @param comprobarRaza raza seleccionada
     */
    private void modificarImagenTipo(Raza comprobarRaza) {
        switch (comprobarRaza) {
            case PROTOS:
                switch (comprobarTipo()) {

                    case LIGERA:
                        imagen.setIcon(new ImageIcon("src\\otros\\zealot.png"));
                        break;
                    case MEDIANA:
                        imagen.setIcon(new ImageIcon("src\\otros\\inmortal.png"));

                        break;
                    case PESADA:
                        imagen.setIcon(new ImageIcon("src\\otros\\coloso.png"));

                        break;
                }
                break;
            case TERRAN:
                switch (comprobarTipo()) {
                    case LIGERA:
                        imagen.setIcon(new ImageIcon("src\\otros\\marine.png"));
                        break;
                    case MEDIANA:
                        imagen.setIcon(new ImageIcon("src\\otros\\tanque.png"));

                        break;
                    case PESADA:
                        imagen.setIcon(new ImageIcon("src\\otros\\thor.png"));

                        break;
                }
                break;
            case ZERG:
                switch (comprobarTipo()) {
                    case LIGERA:
                        imagen.setIcon(new ImageIcon("src\\otros\\zergling.png"));

                        break;
                    case MEDIANA:
                        imagen.setIcon(new ImageIcon("src\\otros\\cuca.png"));

                        break;
                    case PESADA:
                        imagen.setIcon(new ImageIcon("src\\otros\\ultra.png"));

                        break;
                }
                break;
        }
    }
    /**
     * Modifica la imagen segun el tipo de la unidad elegida
     * @param tipo tipo de unidad elegida
     */
    private void modificarImagenRaza(Tipo tipo) {
        switch (tipo) {
            case LIGERA:
                switch (comprobarRaza()) {
                    case PROTOS:
                        imagen.setIcon(new ImageIcon("src\\otros\\zealot.png"));

                        break;
                    case TERRAN:
                        imagen.setIcon(new ImageIcon("src\\otros\\marine.png"));

                        break;
                    case ZERG:
                        imagen.setIcon(new ImageIcon("src\\otros\\zergling.png"));

                        break;
                }
                break;
            case MEDIANA:
                switch (comprobarRaza()) {
                    case PROTOS:
                        imagen.setIcon(new ImageIcon("src\\otros\\inmortal.png"));

                        break;
                    case TERRAN:
                        imagen.setIcon(new ImageIcon("src\\otros\\tanque.png"));

                        break;
                    case ZERG:
                        imagen.setIcon(new ImageIcon("src\\otros\\cuca.png"));

                        break;
                }
                break;
            case PESADA:
                switch (comprobarRaza()) {
                    case PROTOS:
                        imagen.setIcon(new ImageIcon("src\\otros\\coloso.png"));

                        break;
                    case TERRAN:
                        imagen.setIcon(new ImageIcon("src\\otros\\thor.png"));

                        break;
                    case ZERG:
                        imagen.setIcon(new ImageIcon("src\\otros\\ultra.png"));

                        break;
                }
                break;
        }
    }
}
