/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import informacion.*;

import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Ventana buscar
 *
 * @author Rafael Navarro Prieto
 * @version 1.0
 *
 */
public class Buscar extends javax.swing.JDialog {

	/**
	 * clase que se utiliza para los mensajes de error o de información
	 */
	protected final JPanel contentPanel = new JPanel();
	/**
	 * Indices para la visualziación
	 *
	 */
	int indiceTotal, indiceRaza, indiceTipo = 0;
	/**
	 * Jframe que contiene la ventana principal
	 */
	JFrame ventanaPrincipal;

	/**
	 * Constructor
	 *
	 * @param principal
	 *            ventana principal
	 */
	public Buscar(JFrame principal) {
		super();
		initComponents();
		setTitle(Intermediaria.archivo.getName() + " - Almacen de unidades - "
				+ Intermediaria.getFecha());
		// botones limpiar
		limpiar.setEnabled(false);
		// opción de raza
		protos.setEnabled(false);
		terran.setEnabled(false);
		zerg.setEnabled(false);
		// el buscardor completo
		buscar.setEnabled(false);
		// opción de tipo
		ligera.setEnabled(false);
		mediana.setEnabled(false);
		pesada.setEnabled(false);
		// marcamos opciones por defecto
		protos1.setSelected(true);
		ligera2.setSelected(true);
		// reinicia valores por defecto de las diferentes pestañas
		reiniciarValoresRaza();
		reiniciarValoresTipo();
		// visualización de la primera unidad
		mostrarUnidad(indiceTotal);
		comprobarBotones();
		ventanaPrincipal = principal;
		setLocationRelativeTo(null);
		imagen1.setVisible(true);// visualizamos la imagen
		modificarImagenRaza(comprobarTipo());

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        raza = new javax.swing.ButtonGroup();
        tipo = new javax.swing.ButtonGroup();
        listaCompleta = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        victorias = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        ataque = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        derrotas = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        pesada = new javax.swing.JRadioButton();
        ligera = new javax.swing.JRadioButton();
        mediana = new javax.swing.JRadioButton();
        jLabel55 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        protos = new javax.swing.JRadioButton();
        zerg = new javax.swing.JRadioButton();
        terran = new javax.swing.JRadioButton();
        jLabel70 = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        escudo = new javax.swing.JLabel();
        anterior = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        probarUnidad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JLabel();
        victorias1 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        ataque1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        derrotas1 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        pesada1 = new javax.swing.JRadioButton();
        ligera1 = new javax.swing.JRadioButton();
        mediana1 = new javax.swing.JRadioButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        protos1 = new javax.swing.JRadioButton();
        zerg1 = new javax.swing.JRadioButton();
        terran1 = new javax.swing.JRadioButton();
        jLabel74 = new javax.swing.JLabel();
        vida1 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        escudo1 = new javax.swing.JLabel();
        anterior1 = new javax.swing.JButton();
        limpiar1 = new javax.swing.JButton();
        buscar1 = new javax.swing.JButton();
        cancelar1 = new javax.swing.JButton();
        siguiente1 = new javax.swing.JButton();
        probarUnidad1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        fecha2 = new javax.swing.JLabel();
        victorias2 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        ataque2 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        derrotas2 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        pesada2 = new javax.swing.JRadioButton();
        ligera2 = new javax.swing.JRadioButton();
        mediana2 = new javax.swing.JRadioButton();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        protos2 = new javax.swing.JRadioButton();
        zerg2 = new javax.swing.JRadioButton();
        terran2 = new javax.swing.JRadioButton();
        jLabel81 = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        escudo2 = new javax.swing.JLabel();
        anterior2 = new javax.swing.JButton();
        limpiar2 = new javax.swing.JButton();
        buscar2 = new javax.swing.JButton();
        cancelar2 = new javax.swing.JButton();
        siguiente2 = new javax.swing.JButton();
        probarUnidad2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        imagen1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(670, 500));
        setMinimumSize(new java.awt.Dimension(670, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaCompleta.setBackground(new java.awt.Color(255, 255, 255));
        listaCompleta.setMinimumSize(new java.awt.Dimension(590, 224));
        listaCompleta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                listaCompletaStateChanged(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(590, 224));

        jPanel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel52.setText("Ataque:");

        jLabel53.setText("Derrotas:");

        jLabel54.setText("Vida:");

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Starcraft", 0, 10), new java.awt.Color(0, 0, 255))); // NOI18N

        tipo.add(pesada);
        pesada.setText("Pesada");

        tipo.add(ligera);
        ligera.setText("Ligera");

        tipo.add(mediana);
        mediana.setText("Mediana");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ligera)
                    .addComponent(mediana)
                    .addComponent(pesada))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ligera)
                .addGap(11, 11, 11)
                .addComponent(mediana)
                .addGap(18, 18, 18)
                .addComponent(pesada)
                .addContainerGap())
        );

        jLabel55.setText("Fecha de creación:");

        jLabel69.setText("Nombre :");

        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Raza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Starcraft", 0, 10), new java.awt.Color(0, 0, 255))); // NOI18N

        raza.add(protos);
        protos.setText("Protos");

        raza.add(zerg);
        zerg.setText("Zerg");

        raza.add(terran);
        terran.setText("Terran");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(protos)
                    .addComponent(terran)
                    .addComponent(zerg))
                .addContainerGap())
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(protos)
                .addGap(11, 11, 11)
                .addComponent(terran)
                .addGap(18, 18, 18)
                .addComponent(zerg)
                .addContainerGap())
        );

        jLabel70.setText("Victorias:");

        jLabel71.setFont(new java.awt.Font("Starcraft", 0, 11)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 0, 255));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("UNIDAD");

        jLabel72.setText("Escudo:");

        anterior.setText("<");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        cancelar.setText("Salir");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        siguiente.setText(">");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        probarUnidad.setText("Probar Unidad");
        probarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probarUnidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addComponent(jLabel69)
                                .addGap(6, 6, 6)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel32Layout.createSequentialGroup()
                                        .addComponent(jLabel55)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel32Layout.createSequentialGroup()
                                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel32Layout.createSequentialGroup()
                                                .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(derrotas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel32Layout.createSequentialGroup()
                                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel72)
                                                    .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(victorias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(escudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel32Layout.createSequentialGroup()
                                                .addComponent(jLabel52)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ataque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel32Layout.createSequentialGroup()
                                                .addComponent(jLabel54)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(18, 18, 18)))
                        .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addComponent(anterior)
                                .addGap(2, 2, 2)
                                .addComponent(limpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siguiente))
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelar))))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(probarUnidad)))
                .addGap(128, 128, 128))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(anterior)
                                    .addComponent(limpiar)
                                    .addComponent(siguiente))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buscar)
                                    .addComponent(cancelar))
                                .addGap(18, 18, 18)
                                .addComponent(probarUnidad))))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel69)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel72)
                            .addComponent(escudo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70)
                            .addComponent(victorias, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54)
                            .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addComponent(derrotas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ataque, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, 692, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        listaCompleta.addTab("Lista Completa", jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(590, 224));

        jPanel34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel56.setText("Ataque:");

        jLabel57.setText("Derrotas:");

        jLabel58.setText("Vida:");

        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Starcraft", 0, 10), new java.awt.Color(0, 0, 255))); // NOI18N

        tipo.add(pesada1);
        pesada1.setText("Pesada");

        tipo.add(ligera1);
        ligera1.setText("Ligera");

        tipo.add(mediana1);
        mediana1.setText("Mediana");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ligera1)
                    .addComponent(mediana1)
                    .addComponent(pesada1))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ligera1)
                .addGap(11, 11, 11)
                .addComponent(mediana1)
                .addGap(18, 18, 18)
                .addComponent(pesada1)
                .addContainerGap())
        );

        jLabel59.setText("Fecha de creación:");

        jLabel73.setText("Nombre :");

        jPanel35.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Raza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Starcraft", 0, 10), new java.awt.Color(0, 0, 255))); // NOI18N

        raza.add(protos1);
        protos1.setSelected(true);
        protos1.setText("Protos");

        raza.add(zerg1);
        zerg1.setText("Zerg");

        raza.add(terran1);
        terran1.setText("Terran");

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(protos1)
                    .addComponent(terran1)
                    .addComponent(zerg1))
                .addContainerGap())
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(protos1)
                .addGap(11, 11, 11)
                .addComponent(terran1)
                .addGap(18, 18, 18)
                .addComponent(zerg1)
                .addContainerGap())
        );

        jLabel74.setText("Victorias:");

        jLabel75.setFont(new java.awt.Font("Starcraft", 0, 11)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(0, 0, 255));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("UNIDAD");

        jLabel76.setText("Escudo:");

        anterior1.setText("<");
        anterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior1ActionPerformed(evt);
            }
        });

        limpiar1.setText("Limpiar");
        limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar1ActionPerformed(evt);
            }
        });

        buscar1.setText("Buscar");
        buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar1ActionPerformed(evt);
            }
        });

        cancelar1.setText("Salir");
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        siguiente1.setText(">");
        siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente1ActionPerformed(evt);
            }
        });

        probarUnidad1.setText("Probar Unidad");
        probarUnidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probarUnidad1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addComponent(jLabel73)
                                .addGap(6, 6, 6)
                                .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel34Layout.createSequentialGroup()
                                        .addComponent(jLabel59)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel34Layout.createSequentialGroup()
                                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel34Layout.createSequentialGroup()
                                                .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(derrotas1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel34Layout.createSequentialGroup()
                                                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel76)
                                                    .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(victorias1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(escudo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel34Layout.createSequentialGroup()
                                                .addComponent(jLabel56)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ataque1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel34Layout.createSequentialGroup()
                                                .addComponent(jLabel58)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(18, 18, 18)))
                        .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addComponent(anterior1)
                                .addGap(2, 2, 2)
                                .addComponent(limpiar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siguiente1))
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buscar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelar1))))
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(probarUnidad1)))
                .addGap(128, 128, 128))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(anterior1)
                                    .addComponent(limpiar1)
                                    .addComponent(siguiente1))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buscar1)
                                    .addComponent(cancelar1))
                                .addGap(18, 18, 18)
                                .addComponent(probarUnidad1))))
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel73)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel76)
                            .addComponent(escudo1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel74)
                            .addComponent(victorias1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel58)
                            .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(derrotas1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ataque1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, 692, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        listaCompleta.addTab("Lista por raza", jPanel2);

        jPanel3.setMinimumSize(new java.awt.Dimension(590, 224));

        jPanel36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel60.setText("Ataque:");

        jLabel77.setText("Derrotas:");

        jLabel78.setText("Vida:");

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Starcraft", 0, 10), new java.awt.Color(0, 0, 255))); // NOI18N

        tipo.add(pesada2);
        pesada2.setText("Pesada");

        tipo.add(ligera2);
        ligera2.setSelected(true);
        ligera2.setText("Ligera");

        tipo.add(mediana2);
        mediana2.setText("Mediana");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mediana2)
                            .addComponent(pesada2))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(ligera2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ligera2)
                .addGap(11, 11, 11)
                .addComponent(mediana2)
                .addGap(18, 18, 18)
                .addComponent(pesada2)
                .addContainerGap())
        );

        jLabel79.setText("Fecha de creación:");

        jLabel80.setText("Nombre :");

        jPanel37.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Raza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Starcraft", 0, 10), new java.awt.Color(0, 0, 255))); // NOI18N

        raza.add(protos2);
        protos2.setText("Protos");

        raza.add(zerg2);
        zerg2.setText("Zerg");

        raza.add(terran2);
        terran2.setText("Terran");

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(protos2)
                    .addComponent(terran2)
                    .addComponent(zerg2))
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(protos2)
                .addGap(11, 11, 11)
                .addComponent(terran2)
                .addGap(18, 18, 18)
                .addComponent(zerg2)
                .addContainerGap())
        );

        jLabel81.setText("Victorias:");

        jLabel82.setFont(new java.awt.Font("Starcraft", 0, 11)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 0, 255));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("UNIDAD");

        jLabel83.setText("Escudo:");

        anterior2.setText("<");
        anterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior2ActionPerformed(evt);
            }
        });

        limpiar2.setText("Limpiar");
        limpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar2ActionPerformed(evt);
            }
        });

        buscar2.setText("Buscar");
        buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar2ActionPerformed(evt);
            }
        });

        cancelar2.setText("Salir");
        cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar2ActionPerformed(evt);
            }
        });

        siguiente2.setText(">");
        siguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente2ActionPerformed(evt);
            }
        });

        probarUnidad2.setText("Probar Unidad");
        probarUnidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probarUnidad2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel36Layout.createSequentialGroup()
                                .addComponent(jLabel80)
                                .addGap(6, 6, 6)
                                .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel36Layout.createSequentialGroup()
                                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel36Layout.createSequentialGroup()
                                        .addComponent(jLabel79)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel36Layout.createSequentialGroup()
                                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel36Layout.createSequentialGroup()
                                                .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(derrotas2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel36Layout.createSequentialGroup()
                                                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel83)
                                                    .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(victorias2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(escudo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel36Layout.createSequentialGroup()
                                                .addComponent(jLabel60)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ataque2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel36Layout.createSequentialGroup()
                                                .addComponent(jLabel78)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(18, 18, 18)))
                        .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel36Layout.createSequentialGroup()
                                .addComponent(anterior2)
                                .addGap(2, 2, 2)
                                .addComponent(limpiar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siguiente2))
                            .addGroup(jPanel36Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buscar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelar2))))
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(probarUnidad2)))
                .addGap(128, 128, 128))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel36Layout.createSequentialGroup()
                                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(anterior2)
                                    .addComponent(limpiar2)
                                    .addComponent(siguiente2))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buscar2)
                                    .addComponent(cancelar2))
                                .addGap(18, 18, 18)
                                .addComponent(probarUnidad2))))
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel36Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel80)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel83)
                            .addComponent(escudo2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel81)
                            .addComponent(victorias2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78)
                            .addComponent(vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel77)
                            .addComponent(derrotas2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ataque2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel60))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel79))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, 692, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        listaCompleta.addTab("Lista por tipo", jPanel3);

        getContentPane().add(listaCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 630, 230));

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 650, 230));

        imagen1.setBackground(new java.awt.Color(102, 51, 255));
        imagen1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 102)));
        imagen1.setMaximumSize(new java.awt.Dimension(150, 213));
        imagen1.setMinimumSize(new java.awt.Dimension(150, 213));
        getContentPane().add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 150, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otros/FondoFinal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 680, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_anteriorActionPerformed
		mostrarUnidad(--indiceTotal);
		comprobarBotones();
		modificarImagenRaza(comprobarTipo());

	}// GEN-LAST:event_anteriorActionPerformed

	private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_siguienteActionPerformed
		mostrarUnidad(++indiceTotal);
		comprobarBotones();
		modificarImagenRaza(comprobarTipo());
	}// GEN-LAST:event_siguienteActionPerformed

	private void listaCompletaStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_listaCompletaStateChanged
		indiceTotal = 0;
		mostrarUnidad(indiceTotal);
		comprobarBotones();
		indiceRaza = 0; // reinicio de indices
		reiniciarValoresRaza();// reinicio de elementos
		indiceTipo = 0;
		reiniciarValoresTipo();
		if (jPanel1.isShowing()) {
			modificarImagenRaza(comprobarTipo());
			imagen1.setVisible(true);
		} else {
			imagen1.setIcon(new ImageIcon(""));
			imagen1.setVisible(false);
		}

	}// GEN-LAST:event_listaCompletaStateChanged

	private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelarActionPerformed
		cerrar();
	}// GEN-LAST:event_cancelarActionPerformed

	private void probarUnidadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_probarUnidadActionPerformed
		try {
			iniciarTesteo(Intermediaria.lista.getUnidad(nombre.getText()));
		} catch (UnidadNoExistenteException ex) {
			JOptionPane.showMessageDialog(contentPanel, ex.getMessage(),
					"ERROR!!!!", JOptionPane.ERROR_MESSAGE);

		}
	}// GEN-LAST:event_probarUnidadActionPerformed
	/**
	 * Inicia el testeo de la unidad seleccionada
	 * @param unidad unidad que realizara el testeo
	 */
	private void iniciarTesteo(Unidad unidad) {
		test = new Testeo(unidad, this);
		test.setVisible(true);
		setVisible(false);

	}

	private void anterior1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_anterior1ActionPerformed
		mostrarRaza(--indiceRaza);
		comprobarBotonesRaza();
		modificarImagenTipo(comprobarRaza());
	}// GEN-LAST:event_anterior1ActionPerformed

	private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelar1ActionPerformed
		cerrar();
	}// GEN-LAST:event_cancelar1ActionPerformed

	private void siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_siguiente1ActionPerformed
		mostrarRaza(++indiceRaza);
		comprobarBotonesRaza();
		modificarImagenTipo(comprobarRaza());
	}// GEN-LAST:event_siguiente1ActionPerformed

	private void probarUnidad1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_probarUnidad1ActionPerformed
		try {
			iniciarTesteo(Intermediaria.lista.getUnidad(nombre1.getText()));
		} catch (UnidadNoExistenteException ex) {
			JOptionPane.showMessageDialog(contentPanel, ex.getMessage(),
					"ERROR!!!!", JOptionPane.ERROR_MESSAGE);

		}
	}// GEN-LAST:event_probarUnidad1ActionPerformed

	private void anterior2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_anterior2ActionPerformed
		mostrarTipo(--indiceTipo);
		comprobarBotonesTipo();
		modificarImagenRaza(comprobarTipo());
	}// GEN-LAST:event_anterior2ActionPerformed

	private void cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelar2ActionPerformed
		cerrar();
	}// GEN-LAST:event_cancelar2ActionPerformed

	private void siguiente2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_siguiente2ActionPerformed
		mostrarTipo(++indiceTipo);
		comprobarBotonesTipo();
		modificarImagenRaza(comprobarTipo());
	}// GEN-LAST:event_siguiente2ActionPerformed

	private void probarUnidad2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_probarUnidad2ActionPerformed
		try {
			iniciarTesteo(Intermediaria.lista.getUnidad(nombre2.getText()));
		} catch (UnidadNoExistenteException ex) {
			JOptionPane.showMessageDialog(contentPanel, ex.getMessage(),
					"ERROR!!!!", JOptionPane.ERROR_MESSAGE);

		}
	}// GEN-LAST:event_probarUnidad2ActionPerformed

	private void buscar1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buscar1ActionPerformed
		mostrarRaza(indiceRaza);
		comprobarBotonesRaza();
		modificarImagenRaza(comprobarTipo());
	}// GEN-LAST:event_buscar1ActionPerformed

	private void limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_limpiar1ActionPerformed
		reiniciarValoresRaza();
		imagen1.setIcon(new ImageIcon(""));
		imagen1.setVisible(false);

	}// GEN-LAST:event_limpiar1ActionPerformed

	private void buscar2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buscar2ActionPerformed
		mostrarTipo(indiceTipo);
		comprobarBotonesTipo();
		modificarImagenRaza(comprobarTipo());
	}// GEN-LAST:event_buscar2ActionPerformed

	private void limpiar2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_limpiar2ActionPerformed
		reiniciarValoresTipo();
		imagen1.setIcon(new ImageIcon(""));
		imagen1.setVisible(false);

	}// GEN-LAST:event_limpiar2ActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		cerrar();
	}// GEN-LAST:event_formWindowClosing

	private void buscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buscarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_buscarActionPerformed

	/**
	 * Array que contiene las unidades segun la busqueda solicitada
	 */
	ArrayList<Unidad> copia = new ArrayList<>();
	/**
	 * Ventana testeo
	 */
	private Testeo test;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton anterior1;
    private javax.swing.JButton anterior2;
    private javax.swing.JLabel ataque;
    private javax.swing.JLabel ataque1;
    private javax.swing.JLabel ataque2;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscar1;
    private javax.swing.JButton buscar2;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar1;
    private javax.swing.JButton cancelar2;
    private javax.swing.JLabel derrotas;
    private javax.swing.JLabel derrotas1;
    private javax.swing.JLabel derrotas2;
    private javax.swing.JLabel escudo;
    private javax.swing.JLabel escudo1;
    private javax.swing.JLabel escudo2;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fecha1;
    private javax.swing.JLabel fecha2;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton ligera;
    private javax.swing.JRadioButton ligera1;
    private javax.swing.JRadioButton ligera2;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton limpiar1;
    private javax.swing.JButton limpiar2;
    private javax.swing.JTabbedPane listaCompleta;
    private javax.swing.JRadioButton mediana;
    private javax.swing.JRadioButton mediana1;
    private javax.swing.JRadioButton mediana2;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JRadioButton pesada;
    private javax.swing.JRadioButton pesada1;
    private javax.swing.JRadioButton pesada2;
    private javax.swing.JButton probarUnidad;
    private javax.swing.JButton probarUnidad1;
    private javax.swing.JButton probarUnidad2;
    private javax.swing.JRadioButton protos;
    private javax.swing.JRadioButton protos1;
    private javax.swing.JRadioButton protos2;
    private javax.swing.ButtonGroup raza;
    private javax.swing.JButton siguiente;
    private javax.swing.JButton siguiente1;
    private javax.swing.JButton siguiente2;
    private javax.swing.JRadioButton terran;
    private javax.swing.JRadioButton terran1;
    private javax.swing.JRadioButton terran2;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.JLabel victorias;
    private javax.swing.JLabel victorias1;
    private javax.swing.JLabel victorias2;
    private javax.swing.JLabel vida;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida2;
    private javax.swing.JRadioButton zerg;
    private javax.swing.JRadioButton zerg1;
    private javax.swing.JRadioButton zerg2;
    // End of variables declaration//GEN-END:variables
	/**
	 * Muestra la unidad de la lista completa
	 *
	 * @param indiceTotal
	 *            posición de la unidad
	 */
	private void mostrarUnidad(int indiceTotal) {
		try {
			nombre.setText(Intermediaria.lista.getUnidadIndice(indiceTotal)
					.getNombre());
			if (Intermediaria.lista.getUnidadIndice(indiceTotal) instanceof Protos) {// Comprobamos
																						// si
																						// es
																						// protos
																						// por
																						// el
																						// escudo
				Protos p = (Protos) Intermediaria.lista
						.getUnidadIndice(indiceTotal);
				escudo.setText(Float.toString(p.getEscudo()));
			} else {
				escudo.setText("0"); // si no es protos escudo es 0
			}

			// Datos básicos
			victorias.setText(Integer.toString(Intermediaria.lista
					.getUnidadIndice(indiceTotal).getVictorias()));
			derrotas.setText(Integer.toString(Intermediaria.lista
					.getUnidadIndice(indiceTotal).getDerrotas()));
			vida.setText(Float.toString(Intermediaria.lista.getUnidadIndice(
					indiceTotal).getVida()));
			ataque.setText(Float.toString(Intermediaria.lista.getUnidadIndice(
					indiceTotal).getAtaque()));
			fecha.setText(Intermediaria.lista.getUnidadIndice(indiceTotal)
					.getFechaDeCreacion());

			// Selección del radio del tipo
			switch (Intermediaria.lista.getUnidadIndice(indiceTotal).getTipo()) {
			case LIGERA:
				ligera.setSelected(true);
				break;
			case MEDIANA:
				mediana.setSelected(true);
				break;
			case PESADA:
				pesada.setSelected(true);
			}

			// Selección del radio de la raza
			if (Intermediaria.lista.getUnidadIndice(indiceTotal) instanceof Protos) {
				protos.setSelected(true);
			} else if (Intermediaria.lista.getUnidadIndice(indiceTotal) instanceof Terran) {
				terran.setSelected(true);
			} else {
				zerg.setSelected(true);
			}

		} catch (UnidadNoExistenteException ex) {
			JOptionPane.showMessageDialog(contentPanel, ex.getMessage(),
					"ERROR!!!!", JOptionPane.ERROR_MESSAGE);

		}

	}

	/**
	 * comprueba los botones de desplazamiento para el buscador general
	 */
	private void comprobarBotones() {
		if (indiceTotal + 1 >= Intermediaria.lista.size()) {
			siguiente.setEnabled(false);
		} else {
			siguiente.setEnabled(true);
		}
		if (indiceTotal - 1 == -1) {
			anterior.setEnabled(false);
		} else {
			anterior.setEnabled(true);
		}
	}

	/**
	 * Muestra una unidad por raza
	 *
	 * @param indiceRaza
	 *            indice de la unidad
	 */
	private void mostrarRaza(int indiceRaza) {
		try {
			// Rellenar copia con las unidades por raza

			copia = Intermediaria.lista.getRaza(devolverRaza());
			nombre1.setText(copia.get(indiceRaza).getNombre());

			if (copia.get(indiceRaza) instanceof Protos) { // Comprobamos si es
															// protos para el
															// campo escudo

				Protos p = (Protos) (copia.get(indiceRaza));
				escudo1.setText(Float.toString(p.getEscudo()));
			} else {
				escudo1.setText("0");
			}

			// Datos básicos de la unidad
			victorias1.setText(Integer.toString(copia.get(indiceRaza)
					.getVictorias()));
			derrotas1.setText(Integer.toString(copia.get(indiceRaza)
					.getDerrotas()));
			vida1.setText(Float.toString(copia.get(indiceRaza).getVida()));
			ataque1.setText(Float.toString(copia.get(indiceRaza).getAtaque()));
			fecha1.setText(copia.get(indiceRaza).getFechaDeCreacion());

			// Selección del radio del tipo
			switch (copia.get(indiceRaza).getTipo()) {
			case LIGERA:
				ligera1.setSelected(true);
				break;
			case MEDIANA:
				mediana1.setSelected(true);
				break;
			case PESADA:
				pesada1.setSelected(true);
			}

			// Selección del radio de la raza
			if (copia.get(indiceRaza) instanceof Protos) {
				protos1.setSelected(true);
			} else if (copia.get(indiceRaza) instanceof Terran) {
				terran1.setSelected(true);
			} else {
				zerg1.setSelected(true);
			}

			// Modificación de los botones y los radio de la raza al buscar una
			// unidad
			limpiar1.setEnabled(true);
			buscar1.setEnabled(false);
			protos1.setEnabled(false);
			terran1.setEnabled(false);
			zerg1.setEnabled(false);
			imagen1.setVisible(true);
		} catch (ListaRazaVaciaExcepcion ex) {
			JOptionPane.showMessageDialog(contentPanel, ex.getMessage(),
					"ERROR!!!!", JOptionPane.ERROR_MESSAGE);
			reiniciarValoresRaza(); // Valores por defecto
		}
	}

	/**
	 * Devulelve la raza de la unidad segun el campo seleccionado
	 *
	 * @return devuelve la raza de la unidad
	 */
	private Raza devolverRaza() {
		if (protos1.isSelected()) {
			return Raza.PROTOS;
		} else if (terran1.isSelected()) {
			return Raza.TERRAN;
		} else {
			return Raza.ZERG;
		}
	}

	/**
	 * Comprueba los botones del buscador por raza
	 */
	private void comprobarBotonesRaza() {
		if (indiceRaza + 1 >= copia.size()) {
			siguiente1.setEnabled(false);
		} else {
			siguiente1.setEnabled(true);
		}
		if (indiceRaza - 1 == -1) {
			anterior1.setEnabled(false);
		} else {
			anterior1.setEnabled(true);
		}
	}

	/**
	 * Comprueba los botones del buscador tipo
	 */
	private void comprobarBotonesTipo() {
		if (indiceTipo + 1 >= copia.size()) {
			siguiente2.setEnabled(false);
		} else {
			siguiente2.setEnabled(true);
		}
		if (indiceTipo - 1 == -1) {
			anterior2.setEnabled(false);
		} else {
			anterior2.setEnabled(true);
		}
	}

	/**
	 * Reinicia los botones del buscador por tipo
	 */
	private void reiniciarValoresTipo() {
		indiceTipo = 0;
		limpiar2.setEnabled(false);
		siguiente2.setEnabled(false);
		anterior2.setEnabled(false);
		nombre2.setText("");
		escudo2.setText("");
		vida2.setText("");
		ataque2.setText("");
		victorias2.setText("");
		derrotas2.setText("");
		fecha2.setText("");
		limpiar2.setEnabled(false);
		buscar2.setEnabled(true);
		ligera2.setEnabled(true);
		ligera2.setSelected(true);
		mediana2.setEnabled(true);
		pesada2.setEnabled(true);
		protos2.setEnabled(false);
		terran2.setEnabled(false);
		zerg2.setEnabled(false);
	}

	/**
	 * Reinicia los botones del buscador por raza
	 */
	private void reiniciarValoresRaza() {
		indiceRaza = 0;
		limpiar1.setEnabled(false);
		siguiente1.setEnabled(false);
		anterior1.setEnabled(false);
		nombre1.setText("");
		escudo1.setText("");
		vida1.setText("");
		ataque1.setText("");
		victorias1.setText("");
		derrotas1.setText("");
		fecha1.setText("");
		limpiar1.setEnabled(false);
		buscar1.setEnabled(true);
		protos1.setEnabled(true);
		protos1.setSelected(true);
		terran1.setEnabled(true);
		zerg1.setEnabled(true);
		ligera1.setEnabled(false);
		mediana1.setEnabled(false);
		pesada1.setEnabled(false);
	}

	/**
	 * Muestra la unidad por tipo
	 *
	 * @param indiceTipo
	 *            posición de la unidad en la lista
	 */
	private void mostrarTipo(int indiceTipo) {
		try {
			// Rellenar copia con las unidades por tipo

			copia = Intermediaria.lista.getTipo(devolverTipo());
			nombre2.setText(copia.get(indiceTipo).getNombre());

			if (copia.get(indiceTipo) instanceof Protos) { // Se comprueba si es
															// protos para el
															// campo escudo
				Protos p = (Protos) (copia.get(indiceTipo));
				escudo2.setText(Float.toString(p.getEscudo()));
			} else {
				escudo2.setText("0");
			}

			// Datos básicos de la unidad
			victorias2.setText(Integer.toString(copia.get(indiceTipo)
					.getVictorias()));
			derrotas2.setText(Integer.toString(copia.get(indiceTipo)
					.getDerrotas()));
			vida2.setText(Float.toString(copia.get(indiceTipo).getVida()));
			ataque2.setText(Float.toString(copia.get(indiceTipo).getAtaque()));
			fecha2.setText(copia.get(indiceTipo).getFechaDeCreacion());

			// Selección del radio del tipo
			switch (copia.get(indiceTipo).getTipo()) {
			case LIGERA:
				ligera2.setSelected(true);
				break;
			case MEDIANA:
				mediana2.setSelected(true);
				break;
			case PESADA:
				pesada2.setSelected(true);
			}

			// Selección del radio de la raza
			if (copia.get(indiceTipo) instanceof Protos) {
				protos2.setSelected(true);
			} else if (copia.get(indiceTipo) instanceof Terran) {
				terran2.setSelected(true);
			} else {
				zerg2.setSelected(true);
			}

			// Modificación de los botones y los radio del tipo al buscar una
			// unidad
			limpiar2.setEnabled(true);
			buscar2.setEnabled(false);
			ligera2.setEnabled(false);
			mediana2.setEnabled(false);
			pesada2.setEnabled(false);
			imagen1.setVisible(true);
		} catch (ListaTipoVaciaExcepcion ex) {
			JOptionPane.showMessageDialog(contentPanel, ex.getMessage(),
					"ERROR!!!!", JOptionPane.ERROR_MESSAGE);
			reiniciarValoresTipo();// Valores por defecto
		}
	}

	/**
	 * Devuelve el tipo de la unidad
	 *
	 * @return devuelve el tipo de unidad
	 */
	private Tipo devolverTipo() {
		if (ligera2.isSelected()) {
			return Tipo.LIGERA;
		} else if (mediana2.isSelected()) {
			return Tipo.MEDIANA;
		} else {
			return Tipo.PESADA;
		}
	}

	/**
	 * Al cerrar el programa
	 */
	private void cerrar() {
		ventanaPrincipal.setVisible(true);
		dispose();
	}

	/**
	 * Compruena el radio seleccionado con respecto al tipo de unidad
	 *
	 * @return devuelve Tipo.LIGERA si el radio seleccionado es
	 *         ligera,Tipo.MEDIANA si el radio seleccionado es MEDIANA o
	 *         Tipo.PESADA si el radio seleccionado es pesada , si no es ninguno
	 *         devuele null
	 */
	private Tipo comprobarTipo() {
		if (ligera.isSelected() || ligera1.isSelected() || ligera2.isSelected()) {
			return Tipo.LIGERA;
		} else if (mediana.isSelected() || mediana1.isSelected()
				|| mediana2.isSelected()) {
			return Tipo.MEDIANA;
		} else if (pesada.isSelected() || pesada1.isSelected()
				|| pesada2.isSelected()) {
			return Tipo.PESADA;
		} else {
			return null;
		}
	}

	/**
	 * Compruena el radio seleccionado con respecto a la raza de la unidad
	 *
	 * @return devuelve Raza.PROTOS si el radio seleccionado es
	 *         protos,Tipo.TERRAN si el radio seleccionado es terran o Tipo.ZERG
	 *         si el radio seleccionado es zerg, si no es ninguno devuelve null
	 */
	private Raza comprobarRaza() {
		if (protos.isSelected() || protos1.isSelected() || protos2.isSelected()) {
			return Raza.PROTOS;
		} else if (terran.isSelected() || terran1.isSelected()
				|| terran2.isSelected()) {
			return Raza.TERRAN;
		} else if (zerg.isSelected() || zerg1.isSelected()
				|| zerg2.isSelected()) {

			return Raza.ZERG;
		} else {
			return null;
		}

	}

	/**
	 * Modifica la imagen segun la raza seleccionada
	 *
	 * @param raza
	 *            raza seleccionada
	 */
	private void modificarImagenTipo(Raza raza) {
		switch (raza) {
		case PROTOS:
			switch (comprobarTipo()) {

			case LIGERA:
				imagen1.setIcon(new ImageIcon("src\\otros\\zealot.png"));
				break;
			case MEDIANA:
				imagen1.setIcon(new ImageIcon("src\\otros\\inmortal.png"));

				break;
			case PESADA:
				imagen1.setIcon(new ImageIcon("src\\otros\\coloso.png"));

				break;
			default:
				imagen1.setIcon(new ImageIcon(""));
				break;
			}
			break;
		case TERRAN:
			switch (comprobarTipo()) {
			case LIGERA:
				imagen1.setIcon(new ImageIcon("src\\otros\\marine.png"));
				break;
			case MEDIANA:
				imagen1.setIcon(new ImageIcon("src\\otros\\tanque.png"));

				break;
			case PESADA:
				imagen1.setIcon(new ImageIcon("src\\otros\\thor.png"));

				break;
			default:
				imagen1.setIcon(new ImageIcon(""));
				break;
			}
			break;
		case ZERG:
			switch (comprobarTipo()) {
			case LIGERA:
				imagen1.setIcon(new ImageIcon("src\\otros\\zergling.png"));

				break;
			case MEDIANA:
				imagen1.setIcon(new ImageIcon("src\\otros\\cuca.png"));

				break;
			case PESADA:
				imagen1.setIcon(new ImageIcon("src\\otros\\ultra.png"));

				break;
			default:
				imagen1.setIcon(new ImageIcon(""));
				break;
			}
			break;
		default:
			imagen1.setIcon(new ImageIcon(""));

			break;
		}
	}

	/**
	 * Modifica la imagen segun el tipo de la unidad elegida
	 *
	 * @param tipo
	 *            tipo de unidad elegida
	 */
	private void modificarImagenRaza(Tipo tipo) {
		switch (tipo) {
		case LIGERA:
			switch (comprobarRaza()) {
			case PROTOS:
				imagen1.setIcon(new ImageIcon("src\\otros\\zealot.png"));

				break;
			case TERRAN:
				imagen1.setIcon(new ImageIcon("src\\otros\\marine.png"));

				break;
			case ZERG:
				imagen1.setIcon(new ImageIcon("src\\otros\\zergling.png"));

				break;
			default:
				imagen1.setIcon(new ImageIcon(""));
				break;
			}
			break;
		case MEDIANA:
			switch (comprobarRaza()) {
			case PROTOS:
				imagen1.setIcon(new ImageIcon("src\\otros\\inmortal.png"));

				break;
			case TERRAN:
				imagen1.setIcon(new ImageIcon("src\\otros\\tanque.png"));

				break;
			case ZERG:
				imagen1.setIcon(new ImageIcon("src\\otros\\cuca.png"));

				break;
			default:
				imagen1.setIcon(new ImageIcon(""));
				break;
			}
			break;
		case PESADA:
			switch (comprobarRaza()) {
			case PROTOS:
				imagen1.setIcon(new ImageIcon("src\\otros\\coloso.png"));

				break;
			case TERRAN:
				imagen1.setIcon(new ImageIcon("src\\otros\\thor.png"));

				break;
			case ZERG:
				imagen1.setIcon(new ImageIcon("src\\otros\\ultra.png"));

				break;
			default:
				imagen1.setIcon(new ImageIcon(""));
				break;
			}
			break;
		default:
			imagen1.setIcon(new ImageIcon(""));

			break;
		}
	}
}
